<a href="https://colab.research.google.com/github/arleyjasg-prog/Lenguajes-de-Programaci-n./blob/main/Gu%C3%ADa_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL

Una base de datos puede definirse como un conjunto de información organizada
mediante estructuras de datos en la que se pueden ejecutar diferentes operaciones
para realizar consultas o visualizar información (Date, 2001).

Para la gestión de bases de datos existen varios lenguajes de programación y, a su
vez, diversos programas (software), los cuales permiten realizar diferentes operaciones
sobre la información contenida en tales bases de datos de manera estructurada y
eficiente. El lenguaje más utilizado para esta gestión es SQL (lenguaje de consultas
estructurado, por sus siglas en inglés structured query language) (Joshi, Gundale y
Jagdale, 2012); para trabajar tal lenguaje se propone el programa MySQL, de carácter
gratuito.
A lo largo de esta unidad, se presenta la información sobre los componentes de una
base de datos, los tipos de relaciones que se pueden crear y las operaciones básicas
que se realizan en la gestión de bases de datos.

# Modelo Relacional

Al momento de generar una base de datos, una de las decisiones más importantes
es determinar el tipo de modelo de datos a utilizar, el cual determina la estructura que
va a adoptar la información dentro de la base de datos, por lo que cada dato dentro de
esta posee un conjunto de propiedades dadas principalmente por el modelo de datos
utilizado (Marqués, 2009).
A través de la historia se han propuesto diversos modelos de datos, sin embargo,
el relacional, propuesto por Edgar Codd en 1970, ha sido el más utilizado. Como
su nombre lo indica, este modelo está basado en relaciones, las cuales pueden ser
entendidas como tablas de datos organizadas en columnas y filas; es decir que, bajo
un modelo relacional, una base de datos es un conjunto de tablas de datos (Quiroz,
2003).
Dentro del modelo cada una de las tablas es independiente, y dentro de su
elaboración bidimensional se debe tener en cuenta que se denominan atributos a las
columnas y registros a las filas. En la figura 1 se puede observar la estructura de una
base de datos bajo un modelo relacional por medio de un ejemplo.

# Relaciones base

Las relaciones base o relaciones reales son aquellas que poseen un nombre y que están
definidas como parte estructural dentro de la base de datos (Marqués, 2009). En el ejemplo
de la figura 1 se pueden notar dos relaciones base (clientes y ciudades), ya que ambas están
definidas e ingresadas directamente dentro de la base de datos.
Al momento de generar relaciones base, se deben tener en cuenta los siguientes
elementos o características:
1. **Nombres de atributos:** estos nombres deben cumplir dos condiciones: no pueden
contener espacios y todos deben ser diferentes. Además, por facilidad de manejo, se
recomienda asignar nombres representativos; por ejemplo, teniendo en cuenta la figura
1, se puede asignar al atributo Razón social los nombres RazSocial o Razon_Social.
2. **Claves:** dentro de las tablas no pueden existir registros duplicados, por lo que se
deben especificar los atributos que hacen únicas cada una de las filas de la tabla, denominados claves primarias. Por ejemplo, en la figura 1, dentro de la relación
CLIENTE se puede asignar el atributo ID_Cliente por clave primaria. Por otro lado,
se deben identificar los atributos que puedan ser compartidos entre una tabla
y otra, con el objetivo de crear vínculos entre ellas, estos se denominan claves
foráneas. Por ejemplo, en la figura 1, se puede generar el atributo Codigo_Ciudad
como clave foránea de la relación CIUDADES dentro de la relación CLIENTE.

3. **Tipos de datos:** para cada uno de los atributos de las tablas debe ingresarse el
tipo de datos que estas pueden contener (texto, números, fechas o algún formato
adicional). En la tabla 1 se muestran los principales tipos de datos y cómo se
deben asociar a un atributo.

4. **Esquema:** este sirve para denotar la estructura de la base de datos de manera
escrita, especificando los atributos que se utilizan dentro de cada relación. Del
ejemplo mostrado en la figura 1 se puede elaborar el siguiente esquema, donde
se subrayan las claves primarias y se encuentran en negrita las claves foráneas.
CLIENTES (ID_Cliente, Razon_Social, Direccion, CodCiudad, Telefono)
CIUDADES (CodCiudad, Nombre_Ciudad, CodProd)

# Relaciones derivadas

Partiendo de las relaciones o tablas generadas para una base de datos se
pueden generar nuevas relaciones como resultado de la aplicación de un número
de operaciones; estas tablas son llamadas relaciones derivadas (Ramírez y Laguna,
2014). De esta forma, las relaciones derivadas se pueden entender como las tablas que
resultan al realizar una consulta sobre una base de datos.
Las consultas dentro de una base de datos se realizan por medio de operaciones
lógicas efectuadas sobre las relaciones, esto se conoce como álgebra relacional
(Quiroz, 2003).
En los siguientes apartados se muestran cada una de las operaciones más utilizadas
para crear relaciones derivadas, utilizando el software MySQL y mediante ejemplos
prácticos.

# Uso de SQL en Python

Para correr los comandos de SQL en Python se importa la bibliotecta estándar de Python **sqlite3**  que permite crear y manejar bases de datos SQLite sin necesidad de instalar un servidor.

**os:** permite interactuar con el sistema de archivos (por ejemplo, para comprobar si existe un archivo o eliminarlo).

**pandas as pd**: se importa para trabajar con DataFrames, aunque en este bloque todavía no se usa, se deja preparado para futuras consultas.

In [ ]:
  import sqlite3, os, pandas as pd

# Definir la ruta del archivo de base de datos.

Se establece la ubicación y el nombre del archivo que contendrá la base de datos SQLite.

En Google Colab, la carpeta /content/ es el directorio de trabajo por defecto.

In [ ]:
db_path = "/content/tienda.db"

## Eliminar archivo previo (opcional)

Si quieres partir completamente de cero, borra el archivo si existe.


os.path.exists(db_path) comprueba si el archivo tienda.db ya existe.

Si existe, os.remove(db_path) lo elimina para partir de cero.

Esto asegura que la base de datos se cree limpia, sin datos antiguos.

# Crear o abrir la base de datos

sqlite3.connect(db_path) abre una conexión a la base de datos:

Si el archivo ya existía, se conecta a él.

Si no existe, lo crea automáticamente.

Esta conexión (conn) será usada para ejecutar sentencias SQL (crear tablas, insertar datos, hacer consultas, etc.).

In [ ]:
conn = sqlite3.connect(db_path)

## Crear un cursor

El cursor es el objeto que permite enviar comandos SQL a la base de datos a través de la conexión (conn).

In [ ]:
cur = conn.cursor()
print("Base creada en:", db_path)

Base creada en: /content/tienda.db

In [ ]:
cur.executescript("""
DROP TABLE IF EXISTS ventas;
CREATE TABLE ventas (
  Cod_venta  INTEGER PRIMARY KEY,
  Fecha      TEXT NOT NULL,        -- formato ISO 'YYYY-MM-DD'
  Vendedor   TEXT NOT NULL,
  Cod_Prod   TEXT NOT NULL,
  Cantidad   INTEGER NOT NULL
);
""")
conn.commit()
print("Tabla 'ventas' creada.")

Tabla 'ventas' creada.

In [ ]:
cur.executescript("""
INSERT INTO ventas (Cod_venta, Fecha, Vendedor, Cod_Prod, Cantidad)
 VALUES
  (1001, '2025-01-05', 'Ana Ruiz',   'P-001', 3),
  (1002, '2025-01-06', 'Luis Pérez', 'P-003', 1),
  (1003, '2025-01-06', 'Ana Ruiz',   'P-002', 5),
  (1004, '2025-01-07', 'Marta Gil',  'P-001', 2),
  (1005, '2025-01-08', 'Luis Pérez', 'P-004', 4),
  (1006, '2025-01-09', 'Ana Ruiz',   'P-005', 2),
  (1007, '2025-01-10', 'Marta Gil',  'P-002', 6),
  (1008, '2025-01-10', 'Carlos Iba', 'P-003', 1),
  (1009, '2025-01-11', 'Ana Ruiz',   'P-004', 3),
  (1010, '2025-01-12', 'Luis Pérez', 'P-005', 7);
""")
conn.commit()
print("Registros insertados.")

Registros insertados.

In [ ]:
df = pd.read_sql_query("SELECT * FROM ventas ORDER BY Cod_venta;", conn)
df

   Cod_venta       Fecha    Vendedor Cod_Prod  Cantidad
0       1001  2025-01-05    Ana Ruiz    P-001         3
1       1002  2025-01-06  Luis Pérez    P-003         1
2       1003  2025-01-06    Ana Ruiz    P-002         5
3       1004  2025-01-07   Marta Gil    P-001         2
4       1005  2025-01-08  Luis Pérez    P-004         4
5       1006  2025-01-09    Ana Ruiz    P-005         2
6       1007  2025-01-10   Marta Gil    P-002         6
7       1008  2025-01-10  Carlos Iba    P-003         1
8       1009  2025-01-11    Ana Ruiz    P-004         3
9       1010  2025-01-12  Luis Pérez    P-005         7

In [ ]:
# Ejemplo: mostrar todo
for fila in cur.execute("SELECT * FROM ventas ORDER BY Cod_venta;"):
    print(fila)

(1001, '2025-01-05', 'Ana Ruiz', 'P-001', 3)
(1002, '2025-01-06', 'Luis Pérez', 'P-003', 1)
(1003, '2025-01-06', 'Ana Ruiz', 'P-002', 5)
(1004, '2025-01-07', 'Marta Gil', 'P-001', 2)
(1005, '2025-01-08', 'Luis Pérez', 'P-004', 4)
(1006, '2025-01-09', 'Ana Ruiz', 'P-005', 2)
(1007, '2025-01-10', 'Marta Gil', 'P-002', 6)
(1008, '2025-01-10', 'Carlos Iba', 'P-003', 1)
(1009, '2025-01-11', 'Ana Ruiz', 'P-004', 3)
(1010, '2025-01-12', 'Luis Pérez', 'P-005', 7)

update

In [ ]:
# Cambiar el vendedor y la cantidad de la venta con Cod_venta = 2
cur.execute("""
UPDATE ventas
SET Vendedor = 'Carlos Iba',
    Cantidad = 8
WHERE Cod_venta = 1002;
""")
conn.commit()

In [ ]:
df = pd.read_sql_query("SELECT * FROM ventas ORDER BY Cod_venta;", conn)
df

   Cod_venta       Fecha    Vendedor Cod_Prod  Cantidad
0       1001  2025-01-05    Ana Ruiz    P-001         3
1       1002  2025-01-06  Carlos Iba    P-003         8
2       1003  2025-01-06    Ana Ruiz    P-002         5
3       1004  2025-01-07   Marta Gil    P-001         2
4       1005  2025-01-08  Luis Pérez    P-004         4
5       1006  2025-01-09    Ana Ruiz    P-005         2
6       1007  2025-01-10   Marta Gil    P-002         6
7       1008  2025-01-10  Carlos Iba    P-003         1
8       1009  2025-01-11    Ana Ruiz    P-004         3
9       1010  2025-01-12  Luis Pérez    P-005         7

DELETE

In [ ]:
# Borrar la venta cuyo Cod_venta sea 2
cur.execute("""
DELETE FROM ventas
WHERE Cod_venta = 1004;
""")
conn.commit()

In [ ]:
df = pd.read_sql_query("SELECT * FROM ventas ORDER BY Cod_venta;", conn)
df

   Cod_venta       Fecha    Vendedor Cod_Prod  Cantidad
0       1001  2025-01-05    Ana Ruiz    P-001         3
1       1002  2025-01-06  Carlos Iba    P-003         8
2       1003  2025-01-06    Ana Ruiz    P-002         5
3       1005  2025-01-08  Luis Pérez    P-004         4
4       1006  2025-01-09    Ana Ruiz    P-005         2
5       1007  2025-01-10   Marta Gil    P-002         6
6       1008  2025-01-10  Carlos Iba    P-003         1
7       1009  2025-01-11    Ana Ruiz    P-004         3
8       1010  2025-01-12  Luis Pérez    P-005         7

SELECT FROM WHERE

In [ ]:
df1 = pd.read_sql_query("""
SELECT *
FROM ventas
WHERE Cantidad >= 3;
""", conn)
df1

   Cod_venta       Fecha    Vendedor Cod_Prod  Cantidad
0       1001  2025-01-05    Ana Ruiz    P-001         3
1       1002  2025-01-06  Carlos Iba    P-003         8
2       1003  2025-01-06    Ana Ruiz    P-002         5
3       1005  2025-01-08  Luis Pérez    P-004         4
4       1007  2025-01-10   Marta Gil    P-002         6
5       1009  2025-01-11    Ana Ruiz    P-004         3
6       1010  2025-01-12  Luis Pérez    P-005         7

In [ ]:
df2 = pd.read_sql_query("""
SELECT Fecha, Vendedor, Cantidad
FROM ventas
WHERE Cantidad >= 3;
""", conn)
df2

        Fecha    Vendedor  Cantidad
0  2025-01-05    Ana Ruiz         3
1  2025-01-06  Carlos Iba         8
2  2025-01-06    Ana Ruiz         5
3  2025-01-08  Luis Pérez         4
4  2025-01-10   Marta Gil         6
5  2025-01-11    Ana Ruiz         3
6  2025-01-12  Luis Pérez         7

In [ ]:
df3 = pd.read_sql_query("""
SELECT Fecha, Vendedor, Cod_Prod,
       Cantidad * 2 AS Cantidad_Doble
FROM ventas
WHERE Cantidad >= 3;
""", conn)
df3

        Fecha    Vendedor Cod_Prod  Cantidad_Doble
0  2025-01-05    Ana Ruiz    P-001               6
1  2025-01-06  Carlos Iba    P-003              16
2  2025-01-06    Ana Ruiz    P-002              10
3  2025-01-08  Luis Pérez    P-004               8
4  2025-01-10   Marta Gil    P-002              12
5  2025-01-11    Ana Ruiz    P-004               6
6  2025-01-12  Luis Pérez    P-005              14

Otros ejemplos

In [ ]:

consulta_2 = """
SELECT Vendedor, SUM(Cantidad) AS Total
FROM ventas
GROUP BY Vendedor
ORDER BY Total DESC;
"""

df2 = pd.read_sql_query(consulta_2, conn)
df2

     Vendedor  Total
0    Ana Ruiz     13
1  Luis Pérez     11
2  Carlos Iba      9
3   Marta Gil      6

**Crear tabla de productos**

In [ ]:

# Conexión a la misma base
conn = sqlite3.connect("/content/tienda.db")
cur = conn.cursor()

# Crear la tabla Productos
cur.executescript("""
DROP TABLE IF EXISTS Productos;

CREATE TABLE Productos (
    Cod_Prod      TEXT PRIMARY KEY,
    Nombre_producto TEXT NOT NULL,
    Precio        REAL NOT NULL
);
""")
conn.commit()
print("Tabla 'Productos' creada.")

Tabla 'Productos' creada.

Insertar registros de ejemplo

In [ ]:
cur.executescript("""
INSERT INTO Productos (Cod_Prod, Nombre_producto, Precio) VALUES
 ('P-001','Teclado', 25.50),
 ('P-002','Mouse',   15.00),
 ('P-003','Monitor', 120.00),
 ('P-004','Impresora', 95.99),
 ('P-005','Parlantes', 40.00);
""")
conn.commit()
print("Datos insertados en 'Productos'.")

Datos insertados en 'Productos'.

In [ ]:
df_prod = pd.read_sql_query("SELECT * FROM Productos;", conn)
df_prod

  Cod_Prod Nombre_producto  Precio
0    P-001         Teclado   25.50
1    P-002           Mouse   15.00
2    P-003         Monitor  120.00
3    P-004       Impresora   95.99
4    P-005       Parlantes   40.00

# Joins de tablas

Hasta aquí se ha explicado la generación de relaciones derivadas como resultado
de una consulta efectuada sobre una tabla. Sin embargo, dichas relaciones pueden
obtenerse de igual manera por medio de operaciones sobre las tablas pertenecientes a una base de datos.

Los joins de tablas hacen parte de las operaciones más utilizadas para crear
relaciones derivadas dentro de bases de datos. A continuación se explican tres joins que se pueden realizar sobre tablas.

## INNER JOIN

Esta operación se utiliza para generar relaciones derivadas entre dos tablas que
comparten algún atributo, es decir, a partir de una relación base, generar una tabla únicamente con los registros que contienen un valor dentro de un atributo que es compartido con otra relación base.

Para ejecutar esta operación, inicialmente se debe escribir la instrucción SELECT, la cual debe estar acompañada de las columnas de la tabla 1 que se desean mostrar en el resultado; posteriormente se debe indicar el nombre de la tabla 1 por medio de la instrucción FROM; luego se debe utilizar la instrucción INNER JOIN, referenciando, además, el nombre de la tabla 2; y finalmente, se debe utilizar la instrucción ON para denotar los atributos que coinciden en cada tabla. La sintaxis de esta función es la siguiente:

SELECT atributo1, atributo2…
FROM [Nombre tabla 1]
INNER JOIN [Nombre tabla 2]
ON atributo tabla 1 = atributo tabla 2;

In [ ]:
consulta = """
SELECT
       v.Fecha,
       v.Vendedor,
       p.Nombre_producto,
       p.Precio,
       v.Cantidad
FROM ventas AS v
INNER JOIN Productos AS p
    ON v.Cod_Prod = p.Cod_Prod;
"""

df_join = pd.read_sql_query(consulta, conn)
df_join

        Fecha    Vendedor Nombre_producto  Precio  Cantidad
0  2025-01-05    Ana Ruiz         Teclado   25.50         3
1  2025-01-06  Carlos Iba         Monitor  120.00         8
2  2025-01-06    Ana Ruiz           Mouse   15.00         5
3  2025-01-08  Luis Pérez       Impresora   95.99         4
4  2025-01-09    Ana Ruiz       Parlantes   40.00         2
5  2025-01-10   Marta Gil           Mouse   15.00         6
6  2025-01-10  Carlos Iba         Monitor  120.00         1
7  2025-01-11    Ana Ruiz       Impresora   95.99         3
8  2025-01-12  Luis Pérez       Parlantes   40.00         7

**Crear un nuevo atributo a partir de atributos de diferentes tablas**
Total_Venta=Cantidad*Precio

In [ ]:
consulta = """
SELECT
       v.Fecha,
       v.Vendedor,
       p.Nombre_producto,
       p.Precio,
       v.Cantidad,
       v.Cantidad * p.Precio AS Total_Venta
FROM ventas AS v
INNER JOIN Productos AS p
    ON v.Cod_Prod = p.Cod_Prod;
"""

df_join = pd.read_sql_query(consulta, conn)
df_join

        Fecha    Vendedor Nombre_producto  Precio  Cantidad  Total_Venta
0  2025-01-05    Ana Ruiz         Teclado   25.50         3        76.50
1  2025-01-06  Carlos Iba         Monitor  120.00         8       960.00
2  2025-01-06    Ana Ruiz           Mouse   15.00         5        75.00
3  2025-01-08  Luis Pérez       Impresora   95.99         4       383.96
4  2025-01-09    Ana Ruiz       Parlantes   40.00         2        80.00
5  2025-01-10   Marta Gil           Mouse   15.00         6        90.00
6  2025-01-10  Carlos Iba         Monitor  120.00         1       120.00
7  2025-01-11    Ana Ruiz       Impresora   95.99         3       287.97
8  2025-01-12  Luis Pérez       Parlantes   40.00         7       280.00

## LEFT JOIN

In [ ]:
# A) En VENTAS: cambiamos una venta a un código inexistente en Productos
cur.execute("""
UPDATE ventas
SET Cod_Prod = 'P-999'        -- no existe en Productos
WHERE Cod_venta = 1005;       -- antes: P-004
""")

# B1) En PRODUCTOS: renombrar P-004 -> P-044 (rompe match con ventas que aún dicen P-004)
cur.execute("""
UPDATE Productos
SET Cod_Prod = 'P-044'
WHERE Cod_Prod = 'P-004';
""")

# B2) En PRODUCTOS: renombrar P-003 -> P-033 (deja a Productos con un código sin ventas;
# y las ventas que tenían P-003 ahora quedan "huérfanas")
cur.execute("""
UPDATE Productos
SET Cod_Prod = 'P-033'
WHERE Cod_Prod = 'P-003';
""")

conn.commit()

Ver efecto de LEFT JOIN (todas las ventas)

In [ ]:

consulta_left = """
SELECT v.Cod_venta, v.Fecha, v.Vendedor, v.Cod_Prod,
       p.Nombre_producto, p.Precio
FROM ventas AS v
LEFT JOIN Productos AS p
  ON v.Cod_Prod = p.Cod_Prod
ORDER BY v.Cod_venta;
"""
df_left = pd.read_sql_query(consulta_left, conn)
df_left

   Cod_venta       Fecha    Vendedor Cod_Prod Nombre_producto  Precio
0       1001  2025-01-05    Ana Ruiz    P-001         Teclado    25.5
1       1002  2025-01-06  Carlos Iba    P-003            None     NaN
2       1003  2025-01-06    Ana Ruiz    P-002           Mouse    15.0
3       1005  2025-01-08  Luis Pérez    P-999            None     NaN
4       1006  2025-01-09    Ana Ruiz    P-005       Parlantes    40.0
5       1007  2025-01-10   Marta Gil    P-002           Mouse    15.0
6       1008  2025-01-10  Carlos Iba    P-003            None     NaN
7       1009  2025-01-11    Ana Ruiz    P-004            None     NaN
8       1010  2025-01-12  Luis Pérez    P-005       Parlantes    40.0

Simular RIGHT JOIN (todas los productos) invirtiendo el LEFT JOIN

In [ ]:
consulta_right_sim = """
SELECT p.Cod_Prod, p.Nombre_producto, p.Precio,
       v.Cod_venta, v.Fecha, v.Vendedor, v.Cantidad
FROM Productos AS p
LEFT JOIN ventas AS v
  ON v.Cod_Prod = p.Cod_Prod
ORDER BY p.Cod_Prod;
"""
df_right = pd.read_sql_query(consulta_right_sim, conn)
df_right

,Cod_Prod,Nombre_producto,Precio,Cod_venta,Fecha,Vendedor,Cantidad
0,P-001,Teclado,25.50,1001.0,2025-01-05,Ana Ruiz,3.0
1,P-002,Mouse,15.00,1003.0,2025-01-06,Ana Ruiz,5.0
2,P-002,Mouse,15.00,1007.0,2025-01-10,Marta Gil,6.0
3,P-005,Parlantes,40.00,1006.0,2025-01-09,Ana Ruiz,2.0
4,P-005,Parlantes,40.00,1010.0,2025-01-12,Luis Pérez,7.0
5,P-033,Monitor,120.00,NaN,None,None,NaN
6,P-044,Impresora,95.99,NaN,None,None,NaN

### Agrupamiento Group by

## Agrupamiento con GROUP BY

La cláusula `GROUP BY` en SQL se utiliza para agrupar filas que tienen los mismos valores en una o más columnas. Esto se hace a menudo en conjunto con funciones de agregación (como `COUNT()`, `SUM()`, `AVG()`, `MIN()`, `MAX()`) para realizar cálculos en cada grupo de filas.

Imagina que tienes una tabla de ventas y quieres saber la cantidad total vendida por cada vendedor. No te interesa ver cada venta individual, sino el resumen por vendedor. Aquí es donde `GROUP BY` es útil.

La sintaxis básica es:

In [ ]:
consulta_group_by = """
SELECT Vendedor, SUM(Cantidad) AS Total_Cantidad_Vendida
FROM ventas
GROUP BY Vendedor
ORDER BY Total_Cantidad_Vendida DESC;
"""

df_group_by = pd.read_sql_query(consulta_group_by, conn)
df_group_by

     Vendedor  Total_Cantidad_Vendida
0    Ana Ruiz                      13
1  Luis Pérez                      11
2  Carlos Iba                       9
3   Marta Gil                       6

In [ ]:
consulta_cantidad_por_producto = """
SELECT Cod_Prod, SUM(Cantidad) AS Total_Cantidad_Vendida
FROM ventas
GROUP BY Cod_Prod
ORDER BY Total_Cantidad_Vendida DESC;
"""

df_cantidad_por_producto = pd.read_sql_query(consulta_cantidad_por_producto, conn)
df_cantidad_por_producto

  Cod_Prod  Total_Cantidad_Vendida
0    P-002                      11
1    P-005                       9
2    P-003                       9
3    P-999                       4
4    P-004                       3
5    P-001                       3

In [ ]:
consulta_ventas_por_vendedor = """
SELECT
    v.Vendedor,
    SUM(v.Cantidad * p.Precio) AS Total_Ventas_Dinero
FROM ventas AS v
INNER JOIN Productos AS p
    ON v.Cod_Prod = p.Cod_Prod
GROUP BY v.Vendedor
ORDER BY Total_Ventas_Dinero DESC;
"""

df_ventas_por_vendedor = pd.read_sql_query(consulta_ventas_por_vendedor, conn)
df_ventas_por_vendedor

     Vendedor  Total_Ventas_Dinero
0  Luis Pérez                280.0
1    Ana Ruiz                231.5
2   Marta Gil                 90.0

Para convertir una tabla de Excel a SQL:

1.  **Cargar el archivo de Excel:** Primero, necesitas cargar el archivo `.xlsx` o `.xls` en un DataFrame de pandas. Si el archivo está en tu Google Drive, necesitarás montarlo primero. Si lo subes directamente a Colab, estará en el directorio `/content/`.
2.  **Guardar el DataFrame en la base de datos SQL:** Usa el método `to_sql()` del DataFrame, especificando el nombre de la nueva tabla SQL, la conexión a la base de datos y cómo manejar las tablas existentes.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Una vez que hayas ejecutado la celda anterior y montado tu Google Drive, podrás acceder a tus archivos en `/content/drive/My Drive/`.

Ahora, voy a modificar la celda de carga del archivo Excel para que apunte a esta ubicación. **Recuerda actualizar la ruta en el código si tu archivo no está directamente en "My Drive" o si tiene un nombre diferente.**

In [ ]:
# Suponiendo que ya tienes un archivo de Excel llamado 'mi_archivo.xlsx'
# en el directorio /content/

# Paso 1: Cargar el archivo de Excel en un DataFrame de pandas
try:
    # *** MODIFICA LA RUTA DEL ARCHIVO AQUI ***
    # Ejemplo: '/content/drive/My Drive/mi_archivo.xlsx'
    # Si está en una subcarpeta: '/content/drive/My Drive/Carpeta/mi_archivo.xlsx'
    df_excel = pd.read_excel('/content/drive/My Drive/excel_SQL.xlsx')
    print("Archivo de Excel cargado exitosamente.")
    display(df_excel.head())

    # Paso 2: Guardar el DataFrame en la base de datos SQLite
    # 'replace' eliminará la tabla si ya existe y creará una nueva
    # 'index=False' evita que pandas escriba el índice del DataFrame como una columna en SQL
    df_excel.to_sql('nueva_tabla_desde_excel', conn, if_exists='replace', index=False)

    print("\nDataFrame guardado como tabla SQL 'nueva_tabla_desde_excel'.")

    # Verificar que la tabla fue creada leyendo de ella
    df_sql_verificacion = pd.read_sql_query("SELECT * FROM nueva_tabla_desde_excel LIMIT 5;", conn)
    print("\nDatos de la nueva tabla SQL:")
    display(df_sql_verificacion)

except FileNotFoundError:
    print("Error: Asegúrate de que la ruta del archivo sea correcta y que el archivo exista en tu Google Drive.")
except Exception as e:
    print(f"Ocurrió un error: {e}")

Archivo de Excel cargado exitosamente.

,Fecha Ventas,Sede,Nombre del Producto,Código Facturación,Proveedor,Unidades Vendidas,Precio Unitario,total
0,2024-05-10,Central,Producto E,FAC-010,ProveeCuatro,1,27.08,27.08
1,2024-01-14,Central,Producto E,FAC-027,ProveeCinco,1,39.71,39.71
2,2024-02-22,Central,Producto E,FAC-047,ProveeCinco,1,48.18,48.18
3,2024-01-26,Oeste,Producto D,FAC-034,ProveeCuatro,2,26.05,52.10
4,2024-01-18,Sur,Producto E,FAC-035,ProveeCuatro,10,5.72,57.20

DataFrame guardado como tabla SQL 'nueva_tabla_desde_excel'.

Datos de la nueva tabla SQL:

,Fecha Ventas,Sede,Nombre del Producto,Código Facturación,Proveedor,Unidades Vendidas,Precio Unitario,total
0,2024-05-10,Central,Producto E,FAC-010,ProveeCuatro,1,27.08,27.08
1,2024-01-14,Central,Producto E,FAC-027,ProveeCinco,1,39.71,39.71
2,2024-02-22,Central,Producto E,FAC-047,ProveeCinco,1,48.18,48.18
3,2024-01-26,Oeste,Producto D,FAC-034,ProveeCuatro,2,26.05,52.10
4,2024-01-18,Sur,Producto E,FAC-035,ProveeCuatro,10,5.72,57.20

**Notas importantes:**

*   Reemplaza `'mi_archivo.xlsx'` con el nombre real de tu archivo de Excel.
*   Reemplaza `'nueva_tabla_desde_excel'` con el nombre que quieras darle a tu nueva tabla SQL.
*   El parámetro `if_exists='replace'` es útil si quieres reemplazar la tabla cada vez que ejecutas el código. Otras opciones comunes son `'fail'` (lanzar un error si la tabla existe) y `'append'` (agregar datos a la tabla existente).
*   Asegúrate de que la conexión a la base de datos (`conn`) esté activa.

In [ ]:
# Asignar 'Código Facturación' como clave principal
try:
    cur.execute("ALTER TABLE nueva_tabla_desde_excel ADD PRIMARY KEY (\"Código Facturación\");")
    conn.commit()
    print("La columna 'Código Facturación' ha sido asignada como clave principal.")

    # Opcional: Verificar la estructura de la tabla nuevamente para confirmar el cambio
    print("\nVerificando la estructura de la tabla después de asignar la clave principal:")
    cur.execute("PRAGMA table_info(nueva_tabla_desde_excel);")
    table_info_after = cur.fetchall()
    for col_info in table_info_after:
        print(col_info)

except Exception as e:
    print(f"Ocurrió un error al intentar asignar la clave principal: {e}")
    print("Asegúrate de que la columna 'Código Facturación' no contenga valores duplicados y que no exista ya una clave principal en la tabla.")